### ISSUE TITLE
Knockout-Validation

### ISSUE THREAD

**Issue by ViceIce** [gnaeus/knockout-decorators#1]
Hi

how can i check the validation states if i extend the observable with [Knockout-Validation](/Knockout-Contrib/Knockout-Validation#getting-started)?

Regards

**Comment by gnaeus** [comment]
Sorry for the long wait.

Now I add new function `unwrap`, that simple returns internal observable from decorated object property. See [example](../../#knockout-decorators-unwrap) in Readme.

Or see [JsFiddle](https://jsfiddle.net/1zzboc2a/) with integration of **Knockout-Validation** and **knockout-decorators**.

**Comment by ViceIce** [comment]
Thanks, i will try it.

**Comment by ViceIce** [comment]
It works!

Thanks
