### ISSUE TITLE
Compile esm as es5

### ISSUE THREAD

**Issue by ViceIce** [gnaeus/knockout-decorators#15]
Hi,

according to [pkg.module](https://github.com/rollup/rollup/wiki/pkg.module) the esm code should cuurently be compiled to es5 compatible code.

**Background:** I use webpack 4.x to bundle my knockout code, wich will include the esm code. The esm code is not compatible with older polyfilled browser (like ie11). 

Any chance to compile as es5 code? I can send a PR.

**Workaround:** Use an alias for webpack, wich will load the umd code.
```js
{
  resolve: {
    alias: {
      'knockout-decorators$': require.resolve('knockout-decorators')
    }
  }
}
```

Regards
Michael

**Comment by gnaeus** [comment]
Thanks! I'll try to fix it soon.

**Comment by gnaeus** [comment]
See version 1.2.3
