### ISSUE TITLE
Why hasFocus binding not working?

### ISSUE THREAD

**Issue by sanjuroo** [gnaeus/knockout-decorators#16]
When i have hasFocus binding on input element, it doesn't update observable on focus in and out, when i have observable specified as:
`@observable
    public isFocused: boolean = false;`

but this works as expected:
`public isFocused: KnockoutObservable<boolean> = ko.observable(false);`

Any idea why it is so?

**Comment by gnaeus** [comment]
I've just created [an example](https://codesandbox.io/embed/xl1o2owm9q) for "hasFocus" binding in codesandbox.
And everything works Ok. Can you provide more details about your environment setup?

**Comment by sanjuroo** [comment]
we are currently using knockout 3.4.2, i changed version of knockout in your example and it stopped working. Moving to 3.5.0 however causes us some problems. Is there any other solution or moving to latest knockout version is the only one? thanks.

**Comment by mbest** [comment]
You can use `hasfocus` (all lower case) with 3.4.2.

**Comment by sanjuroo** [comment]
well, that was easy, thanks.

**Comment by mbest** [comment]
See knockout/knockout#2221
