### ISSUE TITLE
With webpack, @components in separate files don't work

### ISSUE THREAD

**Issue by cosmoKenney** [gnaeus/knockout-decorators#4]
In other words, if I move my `@component` decorated viewmodel to my main entry point (app.ts) as specified in my webpack.config.js file, my component works fine.  Whereas, if I move my component to it's own file, it doesn't seem to be included in the bundle. 

I'm kind of new to webpack, so this may be obvious to some, but I'm stumped. 

So I can put this .in app.ts:
```javascript
import { observable, computed, component } from "knockout-decorators";

@component( 'home',  require( "./home.html" ) )
export class Home
{
	@observable Message: string = "Hello World!";
	constructor(params) {
	}
}
```
however if it is in home.ts, the component doesn't work.
I.e. if I do this:
```html
<home></home>
```
in index.html I see the rendered template, or don't depending on the component viewmodel location.

Just fyi, the template (home.html):
```html
<h1>Home</h1>
<hr />
<div>
	<span data-bind="text: Message"></span>
</div>
```
Any ideas?

**Comment by gnaeus** [comment]
Sorry for the long wait! =(

You can use the following project structure:
```
├─ [components]
│  └─ [home]
│     ├─ home.css
│     ├─ home.html
│     └─ home.ts
└─ app.ts
```
__home.css__
```css
.home-message { background: #fafcfe; }
```
__home.html__
```html
<h1>Home</h1>
<hr />
<div class="home-message">
  <span data-bind="text: Message"></span>
</div>
```
__home.ts__
```js
import { observable, computed, component } from "knockout-decorators";

// notice, we not export the component class
// it is unnecessary because @component decorator registers it via
// ko.components.register() global function
@component("home",
  require("./home.html"),
  require("./home.css"))
class Home {
  @observable Message: string = "Hello World!";
  constructor(params) { }
}
```
__app.ts__
```js
import * as ko fpom "knockout";
// we not import any variable from component
// instead webpack will include entire file with it's dependencies to the bundle
// and then home.ts module will be simply executed as IIFE.
import "./components/home/home";

ko.applyBindings();
```

**Comment by cosmoKenney** [comment]
Got it working after much grief with webpack. That's why I closed this. It had nothing to do with the decorators library.

**Comment by gnaeus** [comment]
Ok. Thanks for your reply!

**Comment by cosmoKenney** [comment]
@gnaeus 
Hi, I've run into this again on a new project and I'm sure it's webpack that is causing it. I just cannot 
remember how I fixed it last time. See my comments here: https://gitter.im/Profiscience/ko-component-router

**Comment by nmocruz** [comment]
Dá-me issue here, don't know who to fix, previous link doesnt help

**Comment by nmocruz** [comment]
I found out, I was using a different of knockout  3.5.0-rc2 and for some reason webpack was resolving knockout not in 
node_modules/knockout 
but in 
node_modules/knockout-decorators/node_modules/knockout 

so was duplicated and to solve this I put an alias on webpack.config point to right place.

**Comment by gnaeus** [comment]
Hmm.. Maybe I should change "dependencies" to "peerDependencies" in knockout-decorators `package.json`?
``` 
-"dependencies": {
+"peerDependencies": {
  "knockout": "^3.4.2"
},
```
It cans solve your issues without special Webpack configs.

**Comment by gnaeus** [comment]
@cosmoKenney, @nmocruz, now with knockout-decorators v1.2.2 you can try to remove Webpack's aliases for knockout.
