### ISSUE TITLE
Problem when using decorators with custom bindinghandler

### ISSUE THREAD

**Issue by sanjuroo** [gnaeus/knockout-decorators#8]
I have following classes:
<pre><code>class HelloViewModel {
    @observable language: string;

    constructor(language: string) {
        this.language = language;
    }
}

class HelloViewModel2 {
    language: KnockoutObservable<string>;

    constructor(language: string) {
        this.language = ko.observable(language);
    }
}</code></pre>
and this bindingHandlers based on [StackOverflow](https://stackoverflow.com/questions/12125143/giving-initial-value-to-observable-from-the-html-markup):

<pre><code>ko.bindingHandlers.valueInit = 
{
    init(element, valueAccessor, allBindingsAccessor, data) {
        var value = valueAccessor();
        if (!ko.isWriteableObservable(value)) {
            throw new Error('Knockout "initValue" binding expects an observable.');
        }
        value(element.value);
    }
}

ko.bindingHandlers.valueWithInit = {
    init(element, valueAccessor, allBindings, data, context) {
        ko.applyBindingsToNode(element, { valueInit: valueAccessor() }, context);
        ko.applyBindingsToNode(element, { value: valueAccessor() }, context);
    }
};</code></pre>

and some html:
`<p>Language: <span data-bind="text: language"></span></p>`
`<p>Language: <input data-bind="valueWithInit: language" value="Java"/></p>`

When i do:
`ko.applyBindings(new HelloViewModel2('CSharp'));`
it works as expected, CSharp value is overriden by Java value and displayed correctly in input and span.

But when i do:
`ko.applyBindings(new HelloViewModel('CSharp'));` 
input has value of Java, but span displays CSharp

Where could be problem?

**Comment by gnaeus** [comment]
@sanjuroo, your binding expects that value is `ko.observable`:
```js
if (!ko.isWriteableObservable(value)) throw new Error();
```
But decorated `viewModel.language` is not a `ko.observable`. So we need to use Knockout **Expression Rewriting** to write user's input to non-observable object properties. The same mechanics is used by native `data-bind="value: language"` binding. Your binding handlers should be like this (also see [JSFiddle](http://jsfiddle.net/gnaeus/f0wqz3xn/)):
```js
ko.bindingHandlers.valueWithInit = {
  init(element, valueAccessor, allBindings, data, context) {
    const value = valueAccessor();
    if (ko.isObservable(value) || ko.isWriteableObservable(value)) {
      // value is regular ko.observable
      value(element.value);
      ko.applyBindingsToNode(element, { value  }, context);
    } else {
      // value is writeable object property
      // no matter is it decorated by @observable or not
      const write = allBindings.get("_ko_property_writers").valueWithInit;
      // write initial value to viewModel property
      write(element.value);
      // create computed proxy that should satisfy ko.isObservable()
      // and pass reads to valueAccessor and writes to "_ko_property_writers"
      const proxy = ko.pureComputed({ read: valueAccessor, write });
      ko.applyBindingsToNode(element, { value: proxy }, context);
    }
  }
};
// register "valueWithInit" as two-way binding 
// which supports writing to non-observable object properties
// (generate allBindings.get("_ko_property_writers").valueWithInit)
ko.expressionRewriting["_twoWayBindings"].valueWithInit = true;
```

**Comment by sanjuroo** [comment]
thanks for reply, i finally used knockout-pre-rendered instead of our own bindinghandler and works pretty nice with decorators. But i had to write many other bindinghandlers and your answer pointed me to right direction. Would you consider implementing some utility helper functions for easier writing of binding handlers in next versions?

**Comment by gnaeus** [comment]
I read the code of [knockout-pre-rendered](https://github.com/ErikSchierboom/knockout-pre-rendered) and find that it also uses `"_ko_property_writers"` behind the scenes.

I can write an utility that helps us with registering two-way bindings. But it's not a purpose of **knockout-decorators** package. knockout-decorators works on same abstraction level as [MobX](https://github.com/mobxjs/mobx) — the Model Layer. While knockout bindings is Presentation Layer.

So I create [wiki page](https://github.com/gnaeus/knockout-decorators/wiki/Custom-Two-Way-bindings) with code of this utiliy. Maybe it should be placed in knockout's [main wiki](https://github.com/knockout/knockout/wiki).
