### ISSUE TITLE
Component example PersonView does not work as expected

### ISSUE THREAD

**Issue by Eisenspalter** [gnaeus/knockout-decorators#9]
First things first, great job.
I try to implement your PersonView component example. The age is shown fine but the full name shows [object Object] [object Object]. The full name() method can't resolve this.firstName and this.lastName. Any thoughts what could be the problem?

**Comment by gnaeus** [comment]
@Eisenspalter, you can see this [Pen](https://codepen.io/anon/pen/BPYadp?editors=1010). In my browser everything works fine. Can you please tell me more about your environment?

**Comment by Eisenspalter** [comment]
@gnaeus I really don't know what happens. I implement the PersonView example in an existing huge knockout project. After debugging `this.firstName` and `this.lastName` are observables and no setters in the `fullName` method!?

**Comment by gnaeus** [comment]
Yes, `fullName` is Knockout `pureComputed` with no setter. If you want, you can write:
```js
@computed
get fullName() {
  return this.firstName + " " + this.lastName;
}
set fullName(value) {
  [this.firstName, this.lastName] = value.trim().split(/\s+/g);
}
```
This example defines ES6-getter backed by hidden `ko.pureComputed` and regular ES6-setter that can do whatever you want. Like in MobX.

But I can't help you without knowledge about your project.

**Comment by Eisenspalter** [comment]
I will enable the project in the web for you this week. Then you can debug yourself

**Comment by gnaeus** [comment]
@Eisenspalter, any news on this?

**Comment by gnaeus** [comment]
Closed due to inactivity.
